<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="5" passed="1">
  <reporter-output>
    <line>
      <![CDATA[Alert Text is: null]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="E:\Images.jpeg">Screenshot captured</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="E:\Images.jpeg"><img src="E:\Images.jpeg" height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[Customer added successfully with customer id :6]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="E:\Images.jpeg">Screenshot captured</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="E:\Images.jpeg"><img src="E:\Images.jpeg" height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[Customer added successfully with customer id :7]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="E:\Images.jpeg">Screenshot captured</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="E:\Images.jpeg"><img src="E:\Images.jpeg" height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[Customer added successfully with customer id :8]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="E:\Images.jpeg">Screenshot captured</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href="E:\Images.jpeg"><img src="E:\Images.jpeg" height=200 width=200></a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[Customer added successfully with customer id :9]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="3388" started-at="2018-11-19T15:50:34Z" finished-at="2018-11-19T15:50:37Z">
    <groups>
    </groups>
    <test name="BankManagerLoginTest" duration-ms="1380" started-at="2018-11-19T15:50:34Z" finished-at="2018-11-19T15:50:35Z">
      <class name="testcase.BankManagerLoginTest">
        <test-method status="PASS" signature="loginAsBankManager()[pri:0, instance:testcase.BankManagerLoginTest@75d4a5c2]" name="loginAsBankManager" duration-ms="1135" started-at="2018-11-19T15:50:34Z" finished-at="2018-11-19T15:50:35Z">
          <reporter-output>
            <line>
              <![CDATA[Alert Text is: null]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginAsBankManager -->
      </class> <!-- testcase.BankManagerLoginTest -->
    </test> <!-- BankManagerLoginTest -->
    <test name="AddCustomerTest" duration-ms="1985" started-at="2018-11-19T15:50:35Z" finished-at="2018-11-19T15:50:37Z">
      <class name="testcase.AddCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:testcase.AddCustomerTest@682b2fa]" name="setUp" is-config="true" duration-ms="19929" started-at="2018-11-19T15:50:14Z" finished-at="2018-11-19T15:50:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="addACustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcase.AddCustomerTest@682b2fa]" name="addACustomer" duration-ms="1161" started-at="2018-11-19T15:50:36Z" data-provider="getData" finished-at="2018-11-19T15:50:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[trainer@way2automation.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sdfsdf]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[ngjg]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testcase.AddCustomerTest.addACustomer(AddCustomerTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="E:\Images.jpeg">Screenshot captured</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="E:\Images.jpeg"><img src="E:\Images.jpeg" height=200 width=200></a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[Customer added successfully with customer id :6]]>
            </line>
          </reporter-output>
        </test-method> <!-- addACustomer -->
        <test-method status="FAIL" signature="addACustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcase.AddCustomerTest@682b2fa]" name="addACustomer" duration-ms="214" started-at="2018-11-19T15:50:37Z" data-provider="getData" finished-at="2018-11-19T15:50:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[w2ajava@way2automation.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sdfsdf]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[fdfsdf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testcase.AddCustomerTest.addACustomer(AddCustomerTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="E:\Images.jpeg">Screenshot captured</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="E:\Images.jpeg"><img src="E:\Images.jpeg" height=200 width=200></a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[Customer added successfully with customer id :7]]>
            </line>
          </reporter-output>
        </test-method> <!-- addACustomer -->
        <test-method status="FAIL" signature="addACustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcase.AddCustomerTest@682b2fa]" name="addACustomer" duration-ms="279" started-at="2018-11-19T15:50:37Z" data-provider="getData" finished-at="2018-11-19T15:50:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[seleniumcoaching@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sdffsslkjhfhjkwrwe]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[fdsf]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testcase.AddCustomerTest.addACustomer(AddCustomerTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="E:\Images.jpeg">Screenshot captured</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="E:\Images.jpeg"><img src="E:\Images.jpeg" height=200 width=200></a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[Customer added successfully with customer id :8]]>
            </line>
          </reporter-output>
        </test-method> <!-- addACustomer -->
        <test-method status="FAIL" signature="addACustomer(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:testcase.AddCustomerTest@682b2fa]" name="addACustomer" duration-ms="251" started-at="2018-11-19T15:50:37Z" data-provider="getData" finished-at="2018-11-19T15:50:37Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[corporate@way2automation.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[sdfsdfs]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[dfs]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at testcase.AddCustomerTest.addACustomer(AddCustomerTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<a target="_blank" href="E:\Images.jpeg">Screenshot captured</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href="E:\Images.jpeg"><img src="E:\Images.jpeg" height=200 width=200></a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[Customer added successfully with customer id :9]]>
            </line>
          </reporter-output>
        </test-method> <!-- addACustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:testcase.AddCustomerTest@682b2fa]" name="tearDown" is-config="true" duration-ms="3648" started-at="2018-11-19T15:50:38Z" finished-at="2018-11-19T15:50:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- testcase.AddCustomerTest -->
    </test> <!-- AddCustomerTest -->
  </suite> <!-- Suite -->
</testng-results>
